### ISSUE TITLE
Errors when using in nuxt 3 as a plugin

### ISSUE THREAD

**Issue by itzaks** [wobsoriano/vagmi#31]
Hi! 

Thanks for a good plugin. However it fails when I try to publish with it.
Server logs are as follows:

````Aug 31, 09:46:59 PM: 6d66e910 WARN   [Vue warn]: inject() can only be used inside setup() or functional components.
Aug 31, 09:46:59 PM: 6d66e910 ERROR  Error: `useClient` must be used within `WagmiConfig`.

Read more: https://wagmi.sh/docs/WagmiConfig
    at useClient (file:///var/task/node_modules/vagmi/dist/index.mjs:54:11)
    at useConnect (file:///var/task/node_modules/vagmi/dist/index.mjs:133:18)
    at useWallet (file:///var/task/chunks/app/server.mjs:5407:40)
    at setup (file:///var/task/chunks/app/server.mjs:5524:29)
````

Using it as a plugin like this

````


export default defineNuxtPlugin((nuxtApp) => {
  const runtimeConfig = useRuntimeConfig()

   .....

  const client = createClient({
    autoConnect: true,
    connectors: [injectedConnector, walletConnector],
    provider,
    webSocketProvider,
  });

  nuxtApp.vueApp.use(VagmiPlugin(client));
});

````

**Comment by itzaks** [comment]
Found a workaround:

Seems to work when using it like this:

````
  const plugin = VagmiPlugin(client)
  nuxtApp.vueApp.use(plugin);
  nuxtApp.vueApp.provide(Symbol('vagmi'), plugin);
````

**Comment by nicwands** [comment]
Hi I'm still getting the same error after implementing @itzaks workaround. Any updates on how to fix this?

Thanks!

**Comment by HugoCe17** [comment]
> Hi I'm still getting the same error after implementing @itzaks workaround. Any updates on how to fix this?
> 
> Thanks!

Try this! works for `3.0.0-rc.10`

``` javascript
import { configureChains, createClient, chain, VagmiPlugin } from 'vagmi'
import { publicProvider } from 'vagmi/providers/public'
import { infuraProvider } from 'vagmi/providers/infura'
import { alchemyProvider } from 'vagmi/providers/alchemy'
import { MetaMaskConnector } from 'vagmi/connectors/metaMask'
import { WalletConnectConnector } from 'vagmi/connectors/walletConnect'
import { InjectedConnector } from 'vagmi/connectors/injected'

export default defineNuxtPlugin((nuxtApp) => {
    const { chains, provider, webSocketProvider } = configureChains(
        [
            // chain.polygon,

            chain.polygonMumbai,
            chain.hardhat,
            chain.localhost,
        ],
        [
            alchemyProvider({
                alchemyId: useRuntimeConfig().alchemy.apiKey,
                priority: 0,
                stallTimeout: 1000,
                weight: 1,
            }),
            infuraProvider({ priority: 2, stallTimeout: 1000, weight: 2 }),
            publicProvider({ priority: 1, stallTimeout: 1000, weight: 3 }),
        ]
    )

    const client = createClient({
        autoConnect: true,
        connectors: [
            new MetaMaskConnector({ chains }),
            new WalletConnectConnector({
                chains,
                options: {
                    qrcode: true,
                },
            }),
            new InjectedConnector({
                chains,
                options: {
                    name: 'Injected',
                    shimDisconnect: true,
                },
            }),
        ],
        provider,
        webSocketProvider,
    })

    const vagmi = VagmiPlugin(client)

    nuxtApp.vueApp.use(vagmi)

    return {
        provide: {
            vagmi,
        },
    }
})
